apiVersion: v1
kind: ServiceAccount
metadata:
  name: unicorn-backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unicorn-backend-admin
---
apiVersion: v1
kind: Service
metadata:
  name: unicorn-backend
spec:
  type: ClusterIP
  selector:
    app: unicorn-backend
  ports:
    - name: http1
      protocol: TCP
      port: 10001
      targetPort: http1
---
apiVersion: v1
kind: Service
metadata:
  name: unicorn-backend-admin
spec:
  type: ClusterIP
  selector:
    app: unicorn-backend
  ports:
    - name: http2
      protocol: TCP
      port: 10002
      targetPort: http2
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: unicorn-backend
spec:
  protocol: http
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: unicorn-backend-admin
spec:
  protocol: http
---
apiVersion: v1
kind: Secret
metadata:
  name: unicorn-backend-admin
  annotations:
    kubernetes.io/service-account.name: unicorn-backend-admin
type: kubernetes.io/service-account-token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unicorn-backend
  labels:
    app: unicorn-backend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unicorn-backend
  template:
    metadata:
      labels:
        app: unicorn-backend
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/transparent-proxy: 'false'
        consul.hashicorp.com/connect-service: 'unicorn-backend,unicorn-backend-admin'
        consul.hashicorp.com/connect-service-port: '10001,10002'
        consul.hashicorp.com/connect-service-upstreams: 'unicorn-splitter.svc:10003'
        consul.hashicorp.com/enable-metrics: 'false'
        # consul.hashicorp.com/service-meta-version: 'v1'
    spec:
      serviceAccountName: unicorn-backend
      containers:
        - name: unicorn-backend
          image: nicholasjackson/fake-service:v0.26.0
          # imagePullPolicy: Always       # Probably don't need this
          ports:
            - containerPort: 10001
              name: http1
          # readinessProbe:
          #   httpGet:
          #     scheme: HTTP
          #     path: /
          #     port: 10001
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          env:
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:10001'
            - name: 'NAME'
              value: 'unicorn-backend'
            - name: 'MESSAGE'
              value: 'peekaboo'
            - name: 'UPSTREAM_URIS'
              value: 'http://127.0.0.1:10003'
            - name: 'SERVER_TYPE'
              value: 'http'
            - name: 'TIMING_50_PERCENTILE'
              value: '30ms'
            - name: 'TIMING_90_PERCENTILE'
              value: '60ms'
            - name: 'TIMING_99_PERCENTILE'
              value: '90ms'
            - name: 'TIMING_VARIANCE'
              value: '10'
        - name: unicorn-backend2
          image: nicholasjackson/fake-service:v0.26.0
          # imagePullPolicy: Always       # Probably don't need this
          ports:
            - containerPort: 10002
              name: http2
          # readinessProbe:
          #   httpGet:
          #     scheme: HTTP
          #     path: /
          #     port: 10002
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          env:
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:10002'
            - name: 'NAME'
              value: 'unicorn-backend-admin'
            - name: 'MESSAGE'
              value: 'peekaboo'
            - name: 'SERVER_TYPE'
              value: 'http'
            - name: 'TIMING_50_PERCENTILE'
              value: '30ms'
            - name: 'TIMING_90_PERCENTILE'
              value: '60ms'
            - name: 'TIMING_99_PERCENTILE'
              value: '90ms'
            - name: 'TIMING_VARIANCE'
              value: '10'
