apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: unicorn
spec:
  destination:
    name: unicorn-backend
  sources:
    - name: unicorn-frontend
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: unicorn-admin
spec:
  destination:
    name: unicorn-backend-admin
  sources:
    - name: unicorn-frontend
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: unicorn-splitter
spec:
  destination:
    name: unicorn-splitter
  sources:
    - name: unicorn-backend
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: unicorn-split2
spec:
  destination:
    name: unicorn-split2
  sources:
    - name: unicorn-backend
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: unicorn-split
spec:
  destination:
    name: unicorn-split
  sources:
    - name: unicorn-backend
      action: allow
---
