apiVersion: v1
kind: ServiceAccount
metadata:
  name: unicorn-split
---
apiVersion: v1
kind: Service
metadata:
  name: unicorn-split
spec:
  type: ClusterIP
  selector:
    app: unicorn-split
  ports:
    - name: http1
      protocol: TCP
      port: 10003
      targetPort: http1
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: unicorn-split
spec:
  protocol: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unicorn-split
  labels:
    app: unicorn-split
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unicorn-split
  template:
    metadata:
      labels:
        app: unicorn-split
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/enable-metrics: 'false'
        consul.hashicorp.com/transparent-proxy: 'false'
        # consul.hashicorp.com/service-meta-version: 'v1'
    spec:
      serviceAccountName: unicorn-split
      containers:
        - name: unicorn-split
          image: nicholasjackson/fake-service:v0.26.0
          # imagePullPolicy: Always       # Probably don't need this
          ports:
            - containerPort: 10003
              name: http1
          # readinessProbe:
          #   httpGet:
          #     scheme: HTTP
          #     path: /
          #     port: 10003
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          env:
            - name: 'LISTEN_ADDR'
              value: '127.0.0.1:10003'
            - name: 'NAME'
              value: 'unicorn-split'
            - name: 'MESSAGE'
              value: 'peekaboo'
            - name: 'SERVER_TYPE'
              value: 'http'
            - name: 'TIMING_50_PERCENTILE'
              value: '30ms'
            - name: 'TIMING_90_PERCENTILE'
              value: '60ms'
            - name: 'TIMING_99_PERCENTILE'
              value: '90ms'
            - name: 'TIMING_VARIANCE'
              value: '10'