apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: unicorn-apigw
  namespace: default
spec:
  destination:
    name: unicorn-frontend
  sources:
    - name: consul-api-gateway
      namespace: consul
      action: allow
---

